name: test_datm_lnd

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches: [ develop ]
  workflow_dispatch:
  
jobs:
  latest-stable:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-22.04
    
    env:
      # set token to access gh command
      GH_TOKEN: ${{ github.token }}
      # installation location for application
      APP_INSTALL_DIR: ${{ github.workspace }}/app 
      # installation location for dependencies
      DEP_INSTALL_DIR: ~/.spack-ci
      # option for retention period for artifacts, default is 90 days
      ARTIFACTS_RETENTION_PERIOD: 2

    steps:
      # checkout base repository
      - name: Checkout NoahMP Repository
        path: ${{ env.APP_INSTALL_DIR }}/cdeps
        uses: actions/checkout@v3

      # test component
      - name: Test Component
        uses: uturuncoglu/nuopc-comp-testing@main 
        with:
          dependencies: |
            zlib@1.2.12 
            fms@2022.04
            esmf@8.4.0b15+parallelio
            parallelio@2.5.8+pnetcdf
          dependencies_install_dir: ${{ env.DEP_INSTALL_DIR }}
          app_install_dir: ${{ env.APP_INSTALL_DIR }}

          #comp_build: |
          #  export PATH=${{ env.DEP_INSTALL_DIR }}/view/bin:$PATH
          #  export ESMFMKFILE=${{ env.DEP_INSTALL_DIR }}/view/lib/esmf.mk
          #  export NetCDF_ROOT=`nc-config --prefix`
          #  export FC=gfortran
          #  cd ${{ env.APP_INSTALL_DIR }}/cdeps
          #  mkdir build
          #  cd build
          #  cmake -DCMAKE_INSTALL_PREFIX=${{ env.APP_INSTALL_DIR }} -DOPENMP=ON ../
          #  make
          #  make install

      - name: debug
        run: |
          ls -al ${{ env.APP_INSTALL_DIR }}


      # build and install component
      #- name: Build and Install NoahMP
      #  run: |
      #    export PATH=${{ env.DEP_INSTALL_DIR }}/view/bin:$PATH
      #    export ESMFMKFILE=${{ env.DEP_INSTALL_DIR }}/view/lib/esmf.mk
      #    export NetCDF_ROOT=`nc-config --prefix`
      #    export FC=gfortran
      #    cd ${{ github.workspace }}
      #    mkdir build
      #    cd build
      #    cmake -DCMAKE_INSTALL_PREFIX=${{ env.APP_INSTALL_DIR }} -DOPENMP=ON ../
      #    make
      #    make install



