name: test_datm_lnd

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches: [ develop ]
  # following is required to run action manually
  workflow_dispatch:
  
jobs:
  # do component specific staff
  comp-specific:
    runs-on: ubuntu-22.04

    steps:
      # checkout base repository
      - name: Checkout NoahMP Repository
        uses: actions/checkout@v3

  # install dependencies
  install-deps:
    runs-on: ubuntu-22.04
    uses: uturuncoglu/nuopc-comp-testing/.github/workflows/install-deps.yaml@feature/reusable
    with:
      dependencies: |
        zlib@1.2.12


#fms@2022.04
#esmf@8.4.0b15+parallelio
#parallelio@2.5.8+pnetcdf
#zlib@1.2.12
